# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Murat's blog
tagline:             'NA'
description:         ''
url:                 http://mshagirov.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Murat Shagirov
  url:               https://twitter.com/mshagirov
  email:             murat.shagirov (at) u.nus.edu

# Custom vars
version:             1.0.0
