# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Murat's blog
tagline:             'NA'
description:         'description_here'
url:                 http://mshagirov.github.io
baseurl:             'baseurl__'
paginate:            5

# About/contact
author:
  name:              Murat Shagirov
  url:               https://twitter.com/mshagirov
  email:             murat.shagirov (at) u.nus.edu
